### ISSUE TITLE
Relicense project under BSL

### ISSUE THREAD

**Issue by cmgriffing** [Vexilla/vexilla#12]
I think this project would benefit from being under the BSL for the sake of furthering its development while maintaining the right to not have a competitor spin up the project as their own hosted offering.

See Terraform, CockroachDB, MariaDB, etc.

This would require permission from all current authors and contributors to the project.

@dmmulroy Would you accept this relicensing of work you have contributed and will contribute to the project?

@ryanwinchester Does this sound acceptable to you as well?

This project will be spinning up a CLA (Contributor License Agreement) soon to automate this granting of permission.

An example of the BSL can be found here: https://github.com/hashicorp/terraform/blob/main/LICENSE

**Comment by ryanwinchester** [comment]
No problem here 👍

**Comment by dmmulroy** [comment]
Also no problem with me!

**Comment by cmgriffing** [comment]
This project is now licensed under the BSL with a Change License of MIT. For posterity, at the time of this relicensing there were only 2 other contributors to the project.

Their permissions are captured in a screenshot for the sake of record keeping.

![Relicense_project_under_BSL_·_Issue__12_·_Vexilla_vexilla](https://github.com/Vexilla/vexilla/assets/1195435/753c5da2-9e7e-47d8-8ba2-39bca0fcecdb)
