### ISSUE TITLE
Dark mode of website icon graphics too high contrast?

### ISSUE THREAD

**Issue by ryanwinchester** [Vexilla/vexilla#16]
While in dark mode, the icons have a bright white background on the black background of the page.

This is a lot higher contrast when compared to having a light grey background on white when in light mode.

I find it a bit harsh.

(comparing difference in "A" vs "B" background colors for each photo)

<img width="805" alt="Screenshot 2023-12-18 at 9 37 40 PM" src="https://github.com/Vexilla/vexilla/assets/2897340/142cdfb4-1e9d-4af2-87bd-bad7107e23b6">

<img width="798" alt="Screenshot 2023-12-18 at 9 37 35 PM" src="https://github.com/Vexilla/vexilla/assets/2897340/000a464c-ed2e-4890-9818-84fe3591b512">

**Comment by cmgriffing** [comment]
I fiddled with this a little bit. Let me know what you think. I'm wondering if lightening the background a bit would be a good idea too.

**Comment by ryanwinchester** [comment]
Maybe. I'm not a designer though so I don't know why I opened this.

The difference was jarring to me the first time I saw it, but probably only because I switched between light and dark to compare them.
