### ISSUE TITLE
Rust Client Clippy Warnings

### ISSUE THREAD

**Issue by adam-bates** [Vexilla/vexilla#4]
Hey Chris! It's Snowy 😄 (I don't care about dox, Snowy is connected to me in many ways)

The Rust client has 2 clippy warnings (ignoring `./src/example.rs`):
1.
```
warning: unreachable pattern
   --> src/lib.rs:157:17
    |
157 |                 _ => Err(VexillaError::InvalidShouldFeatureType(feature.value_type())),
    |                 ^
    |
    = note: `#[warn(unreachable_patterns)]` on by default
```
2.
```
warning: field `show_logs` is never read
  --> src/lib.rs:23:5
   |
18 | pub struct VexillaClient {
   |            ------------- field in this struct
...
23 |     show_logs: bool,
   |     ^^^^^^^^^
   |
   = note: `VexillaClient` has derived impls for the traits `Debug` and `Clone`, but these are intentionally ignored during dead code analysis
   = note: `#[warn(dead_code)]` on by default
```

These look like they might be there for future changes? But currently both are unused code. If you'd like, I don't mind creating a quick PR to remove the unused code.

**Comment by cmgriffing** [comment]
I would like to leave `show_logs` for now. I think I'm ok with the unreachable pattern for now, as well.
